/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/polls': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all active polls */
    get: operations['listPolls'];
    put?: never;
    /** Create a new poll */
    post: operations['createPoll'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/polls/{poll_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a specific poll with results */
    get: operations['getPoll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/polls/{poll_id}/vote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cast a vote on a poll */
    post: operations['castVote'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Option: {
      /**
       * Format: uuid
       * @description Unique identifier for the option
       */
      id: string;
      /** @description The option text */
      text: string;
      /** @description Number of votes for this option */
      vote_count: number;
    };
    Poll: {
      /**
       * Format: uuid
       * @description Unique identifier for the poll
       */
      id: string;
      /** @description The poll question */
      question: string;
      /** @description Available options for the poll */
      options: components['schemas']['Option'][];
      /**
       * Format: date-time
       * @description When the poll was created
       */
      created_at: string;
      /** @description Whether the poll is still accepting votes */
      is_active: boolean;
    };
    CreatePollRequest: {
      /** @description The poll question */
      question: string;
      /** @description List of option texts */
      options: string[];
    };
    VoteRequest: {
      /**
       * Format: uuid
       * @description ID of the option to vote for
       */
      option_id: string;
    };
    PollResults: {
      /** Format: uuid */
      poll_id: string;
      total_votes: number;
      options: {
        /** Format: uuid */
        id: string;
        text: string;
        vote_count: number;
        /** Format: float */
        percentage: number;
      }[];
    };
    ErrorResponse: {
      /** @description Error message */
      detail: string;
    };
    ValidationError: {
      detail: {
        loc?: (string | number)[];
        msg?: string;
        type?: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPolls: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of active polls */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Poll'][];
        };
      };
    };
  };
  createPoll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePollRequest'];
      };
    };
    responses: {
      /** @description Poll created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Poll'];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationError'];
        };
      };
    };
  };
  getPoll: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        poll_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Poll details with current results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Poll'];
        };
      };
      /** @description Poll not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  castVote: {
    parameters: {
      query?: never;
      header?: {
        /** @description Session ID to prevent duplicate voting */
        'X-Session-ID'?: string;
      };
      path: {
        poll_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VoteRequest'];
      };
    };
    responses: {
      /** @description Vote cast successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Poll'];
        };
      };
      /** @description Invalid option ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Poll not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Already voted from this session */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
